# trigger

name: Weekly Scraper

on:
  schedule:
    - cron: "0 2 * * 2"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node scripts/scraper.js
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
